runtime: nodejs18 # or another supported version

instance_class: F4

env_variables:
  BUCKET_NAME: "hive-compute.appspot.com"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto